[package]
name = "hello-rust"
version = "0.1.0"
authors = ["Stan <6561374+Mala9898@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
